import type { Metadata } from 'next'
import './globals.css'
import { TRPCProvider } from '@/components/providers/TrpcProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='font-sans antialiased'>
        <TRPCProvider>{children}</TRPCProvider>
      </body>
    </html>
  )
}
