import type { Metadata } from 'next'
import './globals.css'
import { TRPCProvider } from '@/components/providers/TrpcProvider'
import { CopilotProvider } from '@/components/providers/CopilotProvider'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className='font-sans antialiased'>
        <TRPCProvider>
          <CopilotProvider>{children}</CopilotProvider>
        </TRPCProvider>
      </body>
    </html>
  )
}
